#--------------------------------------------------------------
# Simple AWS CodeBuild Config File
#
# Copyleft (c) by Denis Astahov
#--------------------------------------------------------------
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID    : "001617643702"
    ECR_REPO_NAME     : "webapp"
    ECR_IMAGE_TAG     : "latest"

phases:
  install:
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version

  pre_build:
    commands:
      - echo "Login to AWS ECR and get commit id"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 001617643702.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_ID=$(git rev-parse --short HEAD)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t webapp:webapp .
      - docker tag webapp:webapp 001617643702.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
      - docker tag webapp:webapp 001617643702.dkr.ecr.us-east-1.amazonaws.com/webapp:$COMMIT_ID

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 001617643702.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
      - docker push 001617643702.dkr.ecr.us-east-1.amazonaws.com/webapp:$COMMIT_ID
